name = "Parser"
defaultTargets = ["Parser"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "nightly-testing"

[[require]]
name = "UnicodeBasic"
git = "https://github.com/fgdorais/lean4-unicode-basic"
rev = "nightly"

[[lean_lib]]
name = "Parser"

[[lean_exe]]
name = "test"
